name: Zap Security Test

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: scan and combine artifact
    outputs:
      artifacts: ${{steps.combine.outputs.artifacts}}
    
    steps:
          - name: ZAP Scan
            uses: zaproxy/action-api-scan@v0.5.0
            with:
              target: 'https://www.zaproxy.org/'
              allow_issue_writing: false
            env:
              ARTIFACT_NAME: '1'
              
          - name: w3 School
            uses: zaproxy/action-api-scan@v0.5.0
            with:
              target: 'https://www.w3schools.com/java/default.asp'
              allow_issue_writing: false              
            env:
              ARTIFACT_NAME: '2'

          - name: Combine Artifacts
            run: |
              mkdir combined_artifact &&
              chmod -R +w combined_artifact &&
              cp -r ${{ env.ARTIFACT_NAME_1}} ${{env.ARTIFACT_NAME_2 }}/* combined_artifact/
              env:
                ARTIFACT_NAME_1: ${{steps.zap_scan_1.outputs.ARTIFACT_NAME}}                
                ARTIFACT_NAME_2: ${{steps.zap_scan_2.outputs.ARTIFACT_NAME}}

          - name: Upload combined report
            uses: actions/upload-artifact@v2
            with:
                name: combined-artifacts
                path: combined_artifacts
