name: Zap Security Test

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: scan and combine artifact
    outputs:
      artifacts: ${{steps.combine.outputs.artifacts}}
    
    steps:
          - name: ZAP Scan
            uses: zaproxy/action-api-scan@v0.5.0
            with:
              target: 'https://www.dalet.com/'
              allow_issue_writing: false
            env:
              ARTIFACT_NAME: 'Company site'

          - name: Clean up Artifact 
            run: rm -rf ${{steps.zap_scan_1.outputs.ARTIFACT_NAME}}

              
          - name: w3 School
            uses: zaproxy/action-api-scan@v0.5.0
            with:
              target: 'https://www.w3schools.com'
              allow_issue_writing: false              
            env:
              ARTIFACT_NAME: 'W3 School'

          - name: Clean up Artifact 
            run: rm -rf ${{steps.zap_scan_2.outputs.ARTIFACT_NAME}}


          - name: Combine Artifacts
            run: |
              mkdir -p combined_artifact &&
              chmod -R 777 combined_artifact &&
              cp -r ${{ steps.zap_scan_1.outputs.ARTIFACT_NAME_1}}/* combined_artifact/ && chmod -R +w combined_artifact/* && cp -r ${{steps.zap_scan_2.outputs.ARTIFACT_NAME_2 }}/* combined_artifact/
              env:
                ARTIFACT_NAME_1: 'Company Site'     
                ARTIFACT_NAME_2: 'W3 School'
          
          - name: Upload combined report
            uses: actions/upload-artifact@v2
            with:
                name: combined-artifact
                path: combined_artifact
