name: Zap Security Test

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
          - name: ZAP Scan
            uses: zaproxy/action-api-scan@v0.5.0
            with:
              target: 'https://www.example.com/graphql'
